import sys
import os
import joblib
import logging
from pathlib import Path
from datetime import datetime, timezone

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(ROOT_DIR))

import hopsworks
import numpy as np
import pandas as pd

from src.config import (
    HOPSWORKS_API_KEY,
    HOPSWORKS_PROJECT_NAME,
    FEATURE_GROUP_NAME,
    FEATURE_GROUP_VERSION,
    MODEL_NAME_TEMPLATE,
    NON_FEATURE_COLS,
    HORIZONS,
)
from src.feature_engineering import get_final_feature_list
from src.model_trainer import feats_used_per_horizon, predict_next_3_days, load_models_local

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

PREDICTIONS_FG_NAME = "aqi_predictions_fg"
PREDICTIONS_FG_VERSION = 1

AQI_CATEGORIES = [
    ("Good", 0, 50),
    ("Moderate", 51, 100),
    ("Unhealthy for Sensitive Groups", 101, 150),
    ("Unhealthy", 151, 200),
    ("Very Unhealthy", 201, 300),
    ("Hazardous", 301, 500),
]
HAZARD_ALERT_THRESHOLD = 200


def aqi_category(value: float) -> str:
    for name, low, high in AQI_CATEGORIES:
        if low <= value <= high:
            return name
    return "Hazardous"


def load_models_from_registry(mr):
    models = {}
    try:
        for idx in HORIZONS:
            model_name = MODEL_NAME_TEMPLATE.format(horizon=idx)
            logger.info(f"Fetching registered model '{model_name}'...")
            model_meta = mr.get_model(model_name, version=1)
            model_dir = model_meta.download()
            models[f"model_day{idx}"] = joblib.load(os.path.join(model_dir, "model.pkl"))
        logger.info("All 3 horizon models loaded from Hopsworks Model Registry.")
        return models
    except Exception as e:
        logger.warning(f"Could not load models from Hopsworks Model Registry ({e}). Falling back to local models/ dir.")
        local_models, _, _ = load_models_local(in_dir=os.path.join(ROOT_DIR, "models"))
        return local_models


def main():
    logger.info("=== Starting Batch Inference Pipeline ===")

    project = hopsworks.login(
        project=HOPSWORKS_PROJECT_NAME,
        api_key_value=HOPSWORKS_API_KEY,
    )
    feature_store = project.get_feature_store()
    mr = project.get_model_registry()

    # 1. Load all 3 horizon models
    models = load_models_from_registry(mr)

    # 2. Read latest feature row from the Feature Store
    fg = feature_store.get_feature_group(name=FEATURE_GROUP_NAME, version=FEATURE_GROUP_VERSION)
    df_features = fg.read()
    df_features = df_features.sort_values("timestamp_unix").reset_index(drop=True)

    fill_cols = [c for c in df_features.columns if c not in NON_FEATURE_COLS]
    df_features[fill_cols] = df_features[fill_cols].ffill()

    latest_row = df_features.tail(1).reset_index(drop=True)
    latest_ts = str(latest_row["datetime_utc"].iloc[0])
    current_aqi = float(latest_row["epa_aqi"].iloc[0])

    # 3. Reconstruct feature set
    all_feature_cols = [
        c for c in df_features.columns
        if c not in NON_FEATURE_COLS and str(df_features[c].dtype) in ["float64", "int64"]
    ]
    final_features = get_final_feature_list(all_feature_cols)
    feats_per_horizon = feats_used_per_horizon(final_features)

    # 4. Predict 3-day forecast
    predictions = predict_next_3_days(models, latest_row, feats_per_horizon)

    now_utc = datetime.now(timezone.utc)
    
    # Create single-row prediction record
    pred_data = {
        "city": "lahore",
        "generated_at": latest_ts,
        "created_at_unix": int(now_utc.timestamp() * 1000),
        "current_aqi": round(current_aqi, 1),
        "current_category": aqi_category(current_aqi),
        "day1_aqi": float(predictions[1]),
        "day1_category": aqi_category(predictions[1]),
        "day1_hazardous": bool(predictions[1] >= HAZARD_ALERT_THRESHOLD),
        "day2_aqi": float(predictions[2]),
        "day2_category": aqi_category(predictions[2]),
        "day2_hazardous": bool(predictions[2] >= HAZARD_ALERT_THRESHOLD),
        "day3_aqi": float(predictions[3]),
        "day3_category": aqi_category(predictions[3]),
        "day3_hazardous": bool(predictions[3] >= HAZARD_ALERT_THRESHOLD),
    }

    pred_df = pd.DataFrame([pred_data])

    # 5. Insert predictions into Hopsworks Feature Group
    logger.info(f"Writing prediction record to Hopsworks feature group '{PREDICTIONS_FG_NAME}'...")
    pred_fg = feature_store.get_or_create_feature_group(
        name=PREDICTIONS_FG_NAME,
        version=PREDICTIONS_FG_VERSION,
        primary_key=["city", "generated_at"],
        event_time="created_at_unix",
        description="Stores live multi-horizon AQI predictions generated by batch inference."
    )
    pred_fg.insert(pred_df, write_options={"wait_for_job": False})

    logger.info("\n" + "=" * 50)
    logger.info("           3-DAY AIR QUALITY FORECAST              ")
    logger.info("=" * 50)
    logger.info(f"Current AQI: {pred_data['current_aqi']} ({pred_data['current_category']})")
    for h in HORIZONS:
        aqi_val = pred_data[f"day{h}_aqi"]
        cat_val = pred_data[f"day{h}_category"]
        flag = "  ⚠️ HAZARDOUS ALERT" if pred_data[f"day{h}_hazardous"] else ""
        logger.info(f"Day {h}: {aqi_val:.1f} ({cat_val}){flag}")
    logger.info("=" * 50)
    logger.info("Predictions successfully written to Hopsworks!")


if __name__ == "__main__":
    main()